server:
  host: 0.0.0.0
  port: 8080

logger:
  path: logs/app.log
  level: 1

github:
  owner: twn39
  repo: code

site:
  title: 生如夏花

redis:
  host: localhost
  port: 6379
  database: 0
  password: